---
- name: Create {{ ansible_env.HOME }}/.ssh directory (if it doesn't exist)
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory
    mode: '0755'

- name: Create {{ ansible_env.HOME }}/.config directory (if it doesn't exist)
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config'
    state: directory
    mode: '0755'