- name: Create {{ ansible_env.HOME }}/.ssh directory (if it doesn't exist)
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/Code/User'
    state: directory
    mode: '0755'

- name: Copy vscode settings to right place
  ansible.builtin.copy:
    src: '../defaults/vscode-settings.json'
    dest: '{{ ansible_env.HOME }}/.config/Code/User/settings.json'